# Classfication Exersice

### First Step : Download __[ Data](https://www.kaggle.com/lucidlenn/sloan-digital-sky-survey)__  

- ###### Import library of pandas and numpy

In [1]:
import numpy as np
import pandas as pd

- ###### Read data as dataframe

In [3]:
data = pd.read_csv("Skyserver_SQL2_27_2018 6_51_39 PM.csv")
data.head()

objid          ra       dec         u         g         r         i  \
0  1.237650e+18  183.531326  0.089693  19.47406  17.04240  15.94699  15.50342   
1  1.237650e+18  183.598371  0.135285  18.66280  17.21449  16.67637  16.48922   
2  1.237650e+18  183.680207  0.126185  19.38298  18.19169  17.47428  17.08732   
3  1.237650e+18  183.870529  0.049911  17.76536  16.60272  16.16116  15.98233   
4  1.237650e+18  183.883288  0.102557  17.55025  16.26342  16.43869  16.55492   

          z  run  rerun  camcol  field     specobjid   class  redshift  plate  \
0  15.22531  752    301       4    267  3.722360e+18    STAR -0.000009   3306   
1  16.39150  752    301       4    267  3.638140e+17    STAR -0.000055    323   
2  16.80125  752    301       4    268  3.232740e+17  GALAXY  0.123111    287   
3  15.90438  752    301       4    269  3.722370e+18    STAR -0.000111   3306   
4  16.61326  752    301       4    269  3.722370e+18    STAR  0.000590   3306   

     mjd  fiberid  
0  54922      491  
1  51615      541  
2  52023      513  
3  54922      510  
4  54922      512

- ###### Explor data and determin classes 

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   objid      10000 non-null  float64
 1   ra         10000 non-null  float64
 2   dec        10000 non-null  float64
 3   u          10000 non-null  float64
 4   g          10000 non-null  float64
 5   r          10000 non-null  float64
 6   i          10000 non-null  float64
 7   z          10000 non-null  float64
 8   run        10000 non-null  int64  
 9   rerun      10000 non-null  int64  
 10  camcol     10000 non-null  int64  
 11  field      10000 non-null  int64  
 12  specobjid  10000 non-null  float64
 13  class      10000 non-null  object 
 14  redshift   10000 non-null  float64
 15  plate      10000 non-null  int64  
 16  mjd        10000 non-null  int64  
 17  fiberid    10000 non-null  int64  
dtypes: float64(10), int64(7), object(1)
memory usage: 1.4+ MB


In [5]:
data['class'].unique()

array(['STAR', 'GALAXY', 'QSO'], dtype=object)

In [6]:
data['class'].value_counts() 

GALAXY    4998
STAR      4152
QSO        850
Name: class, dtype: int64

- ###### Convert classes into numerical classes : 

- **hint** : use convert function 
```python
def convert(classmat):
    if classmat == "STAR":
        return 0
    elif classmat == "GALAXY":
        return 1
    else :
        return 2
```
- ###### Apply function on column `class` in data. 

In [8]:
def convert(classmat):
    if classmat == "STAR":
        return 0
    elif classmat == "GALAXY":
        return 1
    else :
        return 2
    
    
    
data['class'] = data['class'].apply(convert)
data

objid          ra        dec         u         g         r  \
0     1.237650e+18  183.531326   0.089693  19.47406  17.04240  15.94699   
1     1.237650e+18  183.598371   0.135285  18.66280  17.21449  16.67637   
2     1.237650e+18  183.680207   0.126185  19.38298  18.19169  17.47428   
3     1.237650e+18  183.870529   0.049911  17.76536  16.60272  16.16116   
4     1.237650e+18  183.883288   0.102557  17.55025  16.26342  16.43869   
...            ...         ...        ...       ...       ...       ...   
9995  1.237650e+18  131.316413  51.539547  18.81777  17.47053  16.91508   
9996  1.237650e+18  131.306083  51.671341  18.27255  17.43849  17.07692   
9997  1.237650e+18  131.552562  51.666986  18.75818  17.77784  17.51872   
9998  1.237650e+18  131.477151  51.753068  18.88287  17.91068  17.53152   
9999  1.237650e+18  131.665012  51.805307  19.27586  17.37829  16.30542   

             i         z   run  rerun  camcol  field     specobjid  class  \
0     15.50342  15.22531   752    301       4    267  3.722360e+18      0   
1     16.48922  16.39150   752    301       4    267  3.638140e+17      0   
2     17.08732  16.80125   752    301       4    268  3.232740e+17      1   
3     15.98233  15.90438   752    301       4    269  3.722370e+18      0   
4     16.55492  16.61326   752    301       4    269  3.722370e+18      0   
...        ...       ...   ...    ...     ...    ...           ...    ...   
9995  16.68305  16.50570  1345    301       3    161  5.033450e+17      1   
9996  16.71661  16.69897  1345    301       3    162  5.033400e+17      1   
9997  17.43302  17.42048  1345    301       3    162  8.222620e+18      0   
9998  17.36284  17.13988  1345    301       3    163  5.033400e+17      1   
9999  15.83548  15.50588  1345    301       3    163  5.033410e+17      1   

      redshift  plate    mjd  fiberid  
0    -0.000009   3306  54922      491  
1    -0.000055    323  51615      541  
2     0.123111    287  52023      513  
3    -0.000111   3306  54922      510  
4     0.000590   3306  54922      512  
...        ...    ...    ...      ...  
9995  0.027583    447  51877      246  
9996  0.117772    447  51877      228  
9997 -0.000402   7303  57013      622  
9998  0.014019    447  51877      229  
9999  0.118417    447  51877      233  

[10000 rows x 18 columns]

- ###### Select important features for classification . 

In [9]:
correlations=[]
for i in data.columns:
    correlations.append(data['class'].corr(data[i]))
correlations

[nan,
 0.041189178484010346,
 0.0912486619550133,
 0.28454149449673144,
 0.35735216726470953,
 0.27867829983479087,
 0.20536700835206254,
 0.14944432644875313,
 0.10062725638539086,
 nan,
 0.010269071563927057,
 -0.0026101477590745542,
 -0.4660011896549694,
 1.0,
 0.6210459899757005,
 -0.4660038502740187,
 -0.5278029634683571,
 -0.012668507517816938]

In [12]:
data.columns

Index(['objid', 'ra', 'dec', 'u', 'g', 'r', 'i', 'z', 'run', 'rerun', 'camcol',
       'field', 'specobjid', 'class', 'redshift', 'plate', 'mjd', 'fiberid'],
      dtype='object')

In [22]:
allfeatures=pd.concat([pd.Series(data.columns,name='features'),pd.Series(correlations,name='correlations')], axis=1)
allfeatures

features  correlations
0       objid           NaN
1          ra      0.041189
2         dec      0.091249
3           u      0.284541
4           g      0.357352
5           r      0.278678
6           i      0.205367
7           z      0.149444
8         run      0.100627
9       rerun           NaN
10     camcol      0.010269
11      field     -0.002610
12  specobjid     -0.466001
13      class      1.000000
14   redshift      0.621046
15      plate     -0.466004
16        mjd     -0.527803
17    fiberid     -0.012669

In [27]:
important_feature=allfeatures.query('correlations < 1 and correlations >= 0.1 ')
important_feature

features  correlations
3          u      0.284541
4          g      0.357352
5          r      0.278678
6          i      0.205367
7          z      0.149444
8        run      0.100627
14  redshift      0.621046

- ###### Separate features from classes . 

In [28]:
labels = data['class']
features = data.drop(['ra','dec','objid','rerun','camcol','field','specobjid','plate','mjd','fiberid','class'], axis=1)


In [29]:
labels

0       0
1       0
2       1
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    1
Name: class, Length: 10000, dtype: int64

In [30]:
features

u         g         r         i         z   run  redshift
0     19.47406  17.04240  15.94699  15.50342  15.22531   752 -0.000009
1     18.66280  17.21449  16.67637  16.48922  16.39150   752 -0.000055
2     19.38298  18.19169  17.47428  17.08732  16.80125   752  0.123111
3     17.76536  16.60272  16.16116  15.98233  15.90438   752 -0.000111
4     17.55025  16.26342  16.43869  16.55492  16.61326   752  0.000590
...        ...       ...       ...       ...       ...   ...       ...
9995  18.81777  17.47053  16.91508  16.68305  16.50570  1345  0.027583
9996  18.27255  17.43849  17.07692  16.71661  16.69897  1345  0.117772
9997  18.75818  17.77784  17.51872  17.43302  17.42048  1345 -0.000402
9998  18.88287  17.91068  17.53152  17.36284  17.13988  1345  0.014019
9999  19.27586  17.37829  16.30542  15.83548  15.50588  1345  0.118417

[10000 rows x 7 columns]

- ###### Scaling the data 
- **hint** : use StandardScaler and set `with_mean=True` and ` with_std=True`

In [34]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler(copy=True, with_mean=True, with_std=True)
Features = scaler.fit_transform(features)

- ###### Split data into the Training data and Test data by `random_state=2`and `test_size=0.25`

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Features,labels,random_state=2,test_size=0.25)

- ######  building your model ( LogisticRegression Model )

In [36]:
from sklearn.linear_model import LogisticRegression
LogisticRegressionModel = LogisticRegression(penalty='l2',solver='sag',random_state=33)
LogisticRegressionModel.fit(X_train, y_train)

C:\Users\Asus\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=33, solver='sag', tol=0.0001, verbose=0,
                   warm_start=False)

In [37]:
print('LogisticRegressionModel Train Score is : ' , LogisticRegressionModel.score(X_train, y_train))
print('LogisticRegressionModel Test Score is : ' , LogisticRegressionModel.score(X_test, y_test))
print('LogisticRegressionModel Classes are : ' , LogisticRegressionModel.classes_)
print('LogisticRegressionModel No. of iteratios is : ' , LogisticRegressionModel.n_iter_)

LogisticRegressionModel Train Score is :  0.97
LogisticRegressionModel Test Score is :  0.9748
LogisticRegressionModel Classes are :  [0 1 2]
LogisticRegressionModel No. of iteratios is :  [100]


In [38]:
y_pred = LogisticRegressionModel.predict(X_test)

In [39]:
print('Predicted Value for LogisticRegressionModel is : ' , y_pred[:20])
print('Real Value is :  ' , list(y_test[:20] ) )

Predicted Value for LogisticRegressionModel is :  [1 1 1 1 1 2 1 1 1 0 2 1 0 0 0 2 0 1 1 1]
Real Value is :   [1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 2, 1, 0, 0, 0, 2, 0, 1, 1, 1]


- ###### Calculate Confusion Matrix ,precision,recall and f1-score for first model

In [40]:
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)

Confusion Matrix is : 
 [[1051    5    1]
 [  42 1176    0]
 [   0   15  210]]


In [41]:
from sklearn.metrics import classification_report
ClassificationReport = classification_report(y_test,y_pred)
print('Classification Report is : \n', ClassificationReport )

Classification Report is : 
               precision    recall  f1-score   support

           0       0.96      0.99      0.98      1057
           1       0.98      0.97      0.97      1218
           2       1.00      0.93      0.96       225

    accuracy                           0.97      2500
   macro avg       0.98      0.96      0.97      2500
weighted avg       0.98      0.97      0.97      2500



- ######  building your model ( K-NN Classifier Model  )

In [42]:
from sklearn.neighbors import KNeighborsClassifier

KNNClassifierModel = KNeighborsClassifier(n_neighbors= 5,weights ='uniform', # it can be distance
                                          algorithm='auto') # it can be ball_tree, kd_tree,brute

KNNClassifierModel.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [43]:
print('KNNClassifierModel Train Score is : ' , KNNClassifierModel.score(X_train, y_train))
print('KNNClassifierModel Test Score is : ' , KNNClassifierModel.score(X_test, y_test))

KNNClassifierModel Train Score is :  0.9534666666666667
KNNClassifierModel Test Score is :  0.9372


In [47]:
y_pred_mod_2 = KNNClassifierModel.predict(X_test)

In [50]:
print('Predicted Value for KNNClassifierModel is : ' , y_pred_mod_2[:20])
print('Real Value is :  ' , list(y_test[:20] ) )

Predicted Value for KNNClassifierModel is :  [1 1 1 1 1 2 1 1 1 0 2 1 0 1 0 2 0 1 1 1]
Real Value is :   [1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 2, 1, 0, 0, 0, 2, 0, 1, 1, 1]


- ###### Calculate Confusion Matrix ,precision,recall and f1-score for second model

In [52]:
CM_2 = confusion_matrix(y_test, y_pred_mod_2)
print('Confusion Matrix for model 2 is : \n', CM)

Confusion Matrix for model 2 is : 
 [[1010   45    2]
 [  94 1123    1]
 [   2   13  210]]


In [53]:
ClassificationReport = classification_report(y_test,y_pred_mod_2)
print('Classification Report is : \n', ClassificationReport )

Classification Report is : 
               precision    recall  f1-score   support

           0       0.91      0.96      0.93      1057
           1       0.95      0.92      0.94      1218
           2       0.99      0.93      0.96       225

    accuracy                           0.94      2500
   macro avg       0.95      0.94      0.94      2500
weighted avg       0.94      0.94      0.94      2500

